name: 🐧 Linux Builds
on: [ workflow_call, workflow_dispatch ]

jobs:
  build:
    name: 🐧 Linux ${{ matrix.arch }} ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        platform: [linux]
        target: [template_debug, template_release]
        include:
          - arch: x86_64
            os: ubuntu-22.04
          - arch: arm64
            os: ubuntu-22.04-arm

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup godot-cpp
        uses: ./godot-cpp/.github/actions/setup-godot-cpp
        with:
          platform: ${{ matrix.platform }}

      - name: Restore .scons_cache
        uses: ./godot-cpp/.github/actions/godot-cache-restore
        with:
          scons-cache: ${{ github.workspace }}/.scons-cache/
          cache-name: ${{ matrix.platform }}_${{ matrix.arch }}_${{ matrix.target }}

      - name: Build GDExtension
        shell: sh
        env:
          SCONS_CACHE: ${{ github.workspace }}/.scons-cache/
        run: |
          scons target=${{ matrix.target }} platform=${{ matrix.platform }} arch=${{ matrix.arch }}

      - name: Save .scons_cache
        uses: ./godot-cpp/.github/actions/godot-cache-save
        with:
          scons-cache: ${{ github.workspace }}/.scons-cache/
          cache-name: ${{ matrix.platform }}_${{ matrix.arch }}_${{ matrix.target }}

      - name: Prepare Files
        shell: sh
        run: |
          if [ -d "geracaoprocedural2d/addons/godot2d-dungeon-generation/bin/linux" ]; then
            ls -l geracaoprocedural2d/addons/godot2d-dungeon-generation/bin/linux/
            strip geracaoprocedural2d/addons/godot2d-dungeon-generation/bin/linux/*.so || true
          fi

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: gdext-${{ matrix.platform }}-${{ matrix.arch }}-${{ matrix.target }}
          path: |
            ${{ github.workspace }}/geracaoprocedural2d/addons/godot2d-dungeon-generation/bin/**